services:
  mongo:
    image: mongo:6.0.13
    restart: unless-stopped
    ports:
      - 27017:27017
    healthcheck:
      test: [ "CMD", "echo", "'db.runCommand(/\"ping/\").ok'", "| mongosh", "localhost:27017", "--quiet" ]
      interval: 10s
      start_period: 30s
    volumes:
      - ./mongo:/data/db

  core:
    restart: unless-stopped
    ports:
      - 8080:8080
    build:
      context: ./core
      dockerfile: ./dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}

  gui:
    restart: unless-stopped
    ports:
      - 80:80
    stdin_open: true
    build:
      context: ./gui
      dockerfile: ./dockerfile
      args:
        GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    depends_on:
      - core
