FROM node:18-alpine

WORKDIR /app

COPY . .

RUN touch .env.production

ARG GOOGLE_API_KEY

RUN echo "VITE_GOOGLE_MAPS_API_KEY=${GOOGLE_API_KEY}" > .env.production

RUN npm install

RUN npm run build

RUN npm install -g serve

CMD ["serve", "-s", "dist", "-l", "80"]
